[#1399] Xtext Outline View - Return type styling improvements.
eclipse/xtext-eclipse pull request #1400
Opened 2020-04-12 08:35 UTC by miklossy

- Modify the XtextOutlineTreeProvider to use the same styling for the
rule's return types as JDT does for the method's return type.

Signed-off-by: Tamas Miklossy <miklossy@itemis.de>

2020-04-12 10:05 UTC, szarnekow requested changes
For the sake of consistency we should remove all usages of createXtextStyleAdapter

2020-04-12 16:37 UTC, miklossy commented
Since the createXtextStyleAdapter call is present on different places in the [XtextOutlineTreeProvider](https://github.com/eclipse/xtext-eclipse/blob/ab20b6bc984f974700bdfe5bcf2bf33521f2467a/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/outline/XtextOutlineTreeProvider.java#L64-L70) I would leave it for now as it is and refactor it later on.

2020-04-13 15:10 UTC, szarnekow commented
I don't agree. If I change my coloring settings to italic for data type rules, the outline will look weird for that case, too.

2020-04-13 18:15 UTC, miklossy commented
@szarnekow You are right! I updated the PR as requested.

2020-04-17 14:33 UTC, miklossy commented
There is a test failure, the `org.eclipse.xtext.common.types.ui.notification.TypeResourceUnloaderTest.testCloseEditorAndDiscardWorkingCopy` test case is failing on Jenkins, but I think it is not related to this change. @cdietrich Is this test flaky?

2020-04-17 14:35 UTC, cdietrich commented
yes please create and issue for that (TypeResourceUnloaderTest)

2020-04-17 17:49 UTC, miklossy commented
Thanks for restarting the CI Job @cdietrich , it is green again!

2020-04-24 09:48 UTC, miklossy commented
@szarnekow Please review again!

2020-04-24 10:03 UTC, szarnekow approved these changes
Nice.
While testing this I found the icon in the outline for return types to be weird. Can you please update that, too?

2020-04-24 10:15 UTC, miklossy commented
> While testing this I found the icon in the outline for return types to be weird. Can you please update that, too?

@szarnekow Hmm... I did not get your point. Can you please upload a screenshot that I can better imagine?

2020-04-24 10:32 UTC, szarnekow commented
Filed https://github.com/eclipse/xtext-eclipse/issues/1412

2020-04-24 11:08 UTC, merged